### PR TITLE
this is a preview of PR Feature/sal cpp for code-review

### PR DESCRIPTION
**Pull request by qingfengxia**
I think I still lose my commit history, I merge master instead of rebase, so my commit is at very bottom. 

All my previous commits are squashed, split, Cmake, refactoring work on data and node modules
all in this commit
https://github.com/simple-access-layer/source/pull/12/commits/af41924d61233e7b52bc0376cf49005ef5bd91e2

qingfengxia: merge indepdent repo sal-cpp by git read-tree

### CODE REVIEW

**Comment by CnlPepper** [comment]
This looks like it's gone rather wrong. Can I suggest you backup the branch before making any more changes. I no longer have a copy of this code to salvage mistakes from.

**Comment by CnlPepper** [comment]
Actually my past self was kind to my current self and forked the repo, if you need it in a cleaner state.

**Comment by qingfengxia** [comment]
I branch a new branch on Alex branch, so feature/c_cpp is still there.  for comparison

**Comment by CnlPepper** [comment]
Ah ok, nice. Btw this is Alex. I noticed some activity and got nosey! :)

**Comment by qingfengxia** [comment]
it is just a test PR, so it is closed

**Pull request closed without merging**
